version: "3.10"

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    command: sh -c "uvicorn main:app --host 0.0.0.0 --reload"
    environment:
      - DB_URL=postgresql+asyncpg://postgres:123@localhost:5432/faculdade
    depends_on:
      - postgresql


  postgresql:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    volumes:
      - /var/cache/postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env

  
  postgresql-test:
    image: postgres
    ports:
      - 5433:5432
    volumes:
      - /var/cache/postgres_data_test:/var/lib/postgresql/data
    env_file:
      - ./.env
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    env_file:
      - ./.env
    depends_on:
      - postgresql